roles:
- &role1
  name: role1
- &role2 
  name: role2
users:
- id: user1
  name: user1
  password: test
  roles:
  - *role1
- id: user2
  name: user2
  password: test
  roles:
  - *role2
- id: user3
  name: user3
  password: test
  roles:
  - *role1
  - *role2
- id: guest
  name: guest
  password: test
